const char *lua_script = 
"function check_input(test, result, expected)\n"
"    if tonumber(string.format(\"%.1f\", result)) == expected then\n"
"        print(\"PASSED - \" .. test)\n"
"    else\n"
"        local msg = \"FAILED - \" .. test .. \". Expected: \" .. tostring(expected) .. \", got: \" .. tostring(result)\n"
"        print(msg)\n"
"    end\n"
"end\n"
"\n"
"\n"
"\n"
"function gpio_output_test()\n"
"\n"
"    -- Test GPIO out\n"
"    print(\"Setting pin 2 HIGH\")\n"
"    hardware.gpio.set_output(2, \"HIGH\")\n"
"    hardware.timer.delay_ms(2000)\n"
"\n"
"    check_input(\"Pin 3 is HIGH\",          hardware.gpio.get_input(3),         1)\n"
"\n"
"end\n"
"\n"
"function gpio_input_test()\n"
"    \n"
"    -- Test GPIO in and PUPD\n"
"    print(\"Setting PULL UP on pin 0\")\n"
"    hardware.gpio.set_pulls(0, \"UP\")\n"
"    hardware.timer.delay_ms(2000)\n"
"    check_input(\"Pin 0 is pulled up\",         hardware.gpio.get_input(0),         1)\n"
"    hardware.timer.delay_ms(2000)\n"
"\n"
"    print(\"Setting PULL DOWN on pin 0\")\n"
"    hardware.gpio.set_pulls(0, \"DOWN\")\n"
"    hardware.timer.delay_ms(2000)\n"
"    check_input(\"Pin 0 is pulled down\",         hardware.gpio.get_input(0),         0)\n"
"end\n"
"\n"
"while true do\n"
"    print(\"Running GPIO tests...\")\n"
"    hardware.timer.delay_ms(5000)\n"
"\n"
"    print(\"Running output tests\")\n"
"    gpio_output_test()\n"
"    hardware.timer.delay_ms(2000)\n"
"    print(\"Running input tests\")\n"
"    gpio_input_test()\n"
"end\n"
;
